language: rust

env: CARGO_INCREMENTAL=0

cache:
  cargo: true
  timeout: 450

stages:
  - lint
  - test

jobs:
  include:
    - stage: test
      script:
        - cargo build
        - cargo test
    - stage: lint
      before_script:
        - rustup component add rustfmt-preview
      script:
        - cargo fmt --all -- --write-mode=check
