[package]
name = "electrs"
version = "0.9.0-rc1"
authors = ["Roman Zeyde <me@romanzey.de>"]
description = "An efficient re-implementation of Electrum Server in Rust"
license = "MIT"
homepage = "https://github.com/romanz/electrs"
repository = "https://github.com/romanz/electrs"
keywords = ["bitcoin", "electrum", "server", "index", "database"]
documentation = "https://docs.rs/electrs/"
readme = "README.md"
edition = "2018"
build = "build.rs"

[features]
default = ["metrics"]
metrics = ["prometheus", "tiny_http"]

[package.metadata.configure_me]
spec = "internal/config_specification.toml"

[dependencies]
anyhow = "1.0"
bitcoin = { version = "0.27", features = ["use-serde", "rand"] }
configure_me = "0.4"
crossbeam-channel = "0.5"
dirs-next = "2.0"
env_logger = "0.7"
log = "0.4"
parking_lot = "0.11"
prometheus = { version = "0.12", optional = true }
rayon = "1.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
signal-hook = "0.3"
tiny_http = { version = "0.8", optional = true }

[dependencies.core-rpc]
version = "0.15.0"  # Use bitcoincore-rpc fork for now

[dependencies.electrs-rocksdb]
# support building with Rust 1.41.1 and workaround the following issues:
# https://github.com/romanz/electrs/issues/403 (support building on ARM 32-bit)
# https://github.com/romanz/electrs/issues/469 (dynamic linking on Debian 11)
version = "0.15.0-e1"
default-features = false
# ZSTD is used for data compression
# Snappy is only for checking old DB
features = ["zstd", "snappy"]

[build-dependencies]
configure_me_codegen = "0.4"

[dev-dependencies]
tempfile = "3.2"
