[package]
name = "indexrs"
version = "0.1.0"
authors = ["Roman Zeyde <me@romanzey.de>"]

[dependencies]
bitcoin = "0.12"
byteorder = "1.2.2"
itertools = "0.7.8"
log = "0.4"
reqwest = "0.8.5"
rocksdb = "0.10.0"  #{ path = "../../rust-rocksdb" }
rust-crypto = "^0.2"
rustc-serialize = "0.3"
serde_json = "1.0.13"
simple_logger = "0.5"
time = "0.1.39"
zmq = "0.8"
