[package]
name = "electrs"
version = "0.1.0"
authors = ["Roman Zeyde <me@romanzey.de>"]

[dependencies]
argparse = "0.2"
arrayref = "0.3"
base64 = "0.9"
bincode = "1.0"
bitcoin = "0.13"
chan = "0.1"
chan-signal = "0.3"
error-chain = "0.11"
hex = "0.3"
log = "0.4"
pbr = "1.0"
rocksdb = "0.10"
rust-crypto = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
simplelog = "0.5"
time = "0.1"
