[package]
name = "indexrs"
version = "0.1.0"
authors = ["Roman Zeyde <me@romanzey.de>"]

[dependencies]
argparse = "0.2.1"
arrayref = "0.3.4"
bincode = "1.0.0"
bitcoin = "0.12"
crossbeam = "0.3.2"
itertools = "0.7.8"
log = "0.4"
pbr = "1.0.0"
reqwest = "0.8.5"
rocksdb = "0.10.0"
rust-crypto = "^0.2"
serde = "1.0.37"
serde_derive = "1.0.37"
serde_json = "1.0.13"
simplelog = "0.5.1"
time = "0.1.39"
zmq = "0.8"
