[package]
name = "electrs"
version = "0.9.0"
authors = ["Roman Zeyde <me@romanzey.de>"]
description = "An efficient re-implementation of Electrum Server in Rust"
license = "MIT"
homepage = "https://github.com/romanz/electrs"
repository = "https://github.com/romanz/electrs"
keywords = ["bitcoin", "electrum", "server", "index", "database"]
documentation = "https://docs.rs/electrs/"
readme = "README.md"
edition = "2018"
build = "build.rs"

[features]
default = ["rocksdb/zstd", "prometheus/process"]

[package.metadata.configure_me]
spec = "internal/config_specification.toml"

[dependencies]
anyhow = "1.0"
bitcoin = { version = "0.26", features = ["use-serde", "rand"] }
bitcoincore-rpc = "0.13"
configure_me = "0.4"
crossbeam-channel = "0.5"
dirs-next = "2.0"
env_logger = "0.7"
hyper = "0.10"
log = "0.4"
prometheus = { version = "0.12", default-features = false }
rayon = "1.5"
rocksdb = { git = "https://github.com/romanz/rust-rocksdb", rev = "4554d19b2ff2e34493564b4d868454097c74b693", default-features = false }  # to support building with Rust 1.41.1 and https://github.com/romanz/electrs/issues/403
rust-crypto = "0.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
signal-hook = "0.3"

[build-dependencies]
configure_me_codegen = "0.4"