[package]
name = "indexrs"
version = "0.1.0"
authors = ["Roman Zeyde <me@romanzey.de>"]

[dependencies]
bitcoin = "0.12"
itertools = "0.7.8"
log = "0.4"
reqwest = "0.8.5"
rocksdb = "^0.8.0"
rustc-serialize = "0.3"
serde_json = "1.0.13"
simple_logger = "0.5"
