name: electrs

on: [push, pull_request]

jobs:
  electrs:
    name: Electrum Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: docker build . --rm -t electrs:tests
      - name: Test
        run: docker run -v $PWD/contrib/:/contrib -v $PWD/tests/:/tests --rm electrs:tests bash /tests/run.sh
